// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgAHyLVcqNIwM6trogWqlZurPuE-GPukc',
    appId: '1:964188330291:web:94b1396902fb44c4ef0646',
    messagingSenderId: '964188330291',
    projectId: 'djassaci-8918d',
    authDomain: 'djassaci-8918d.firebaseapp.com',
    storageBucket: 'djassaci-8918d.firebasestorage.app',
    measurementId: 'G-M9SJ5D54CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1XGjz2rOzeaRIjVVNJallPd_sVc4p1c',
    appId: '1:964188330291:android:fe8ea94f97018a0aef0646',
    messagingSenderId: '964188330291',
    projectId: 'djassaci-8918d',
    storageBucket: 'djassaci-8918d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSgBl5WUAcJKmlDVK8E9HQwu7yl-rdWqo',
    appId: '1:964188330291:ios:e06c20eb34364b82ef0646',
    messagingSenderId: '964188330291',
    projectId: 'djassaci-8918d',
    storageBucket: 'djassaci-8918d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSgBl5WUAcJKmlDVK8E9HQwu7yl-rdWqo',
    appId: '1:964188330291:ios:e06c20eb34364b82ef0646',
    messagingSenderId: '964188330291',
    projectId: 'djassaci-8918d',
    storageBucket: 'djassaci-8918d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgAHyLVcqNIwM6trogWqlZurPuE-GPukc',
    appId: '1:964188330291:web:813762b234664f25ef0646',
    messagingSenderId: '964188330291',
    projectId: 'djassaci-8918d',
    authDomain: 'djassaci-8918d.firebaseapp.com',
    storageBucket: 'djassaci-8918d.firebasestorage.app',
    measurementId: 'G-Z5PMRKE0CH',
  );
}
